################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../src/AC3AudioRTPSink.cpp \
../src/AC3AudioRTPSource.cpp \
../src/AMRAudioFileSink.cpp \
../src/AMRAudioRTPSource.cpp \
../src/AMRAudioSource.cpp \
../src/AVIFileSink.cpp \
../src/AudioRTPSink.cpp \
../src/Base64.cpp \
../src/BasicHashTable.cpp \
../src/BasicTaskScheduler.cpp \
../src/BasicTaskScheduler0.cpp \
../src/BasicUDPSink.cpp \
../src/BasicUDPSource.cpp \
../src/BasicUsageEnvironment.cpp \
../src/BitVector.cpp \
../src/CommonPlay.cpp \
../src/CycleQueue.cpp \
../src/DP_RTSP_CLIENT_CycleQueue.cpp \
../src/DP_RTSP_CLIENT_DataQueue.cpp \
../src/DP_RTSP_CLIENT_Interface.cpp \
../src/DVVideoRTPSink.cpp \
../src/DVVideoRTPSource.cpp \
../src/DVVideoStreamFramer.cpp \
../src/DelayQueue.cpp \
../src/DigestAuthentication.cpp \
../src/FileSink.cpp \
../src/FramedFilter.cpp \
../src/FramedSource.cpp \
../src/GSMAudioRTPSink.cpp \
../src/GenericMediaServer.cpp \
../src/GetFrameData.cpp \
../src/GroupEId.cpp \
../src/Groupsock.cpp \
../src/GroupsockHelper.cpp \
../src/H261VideoRTPSource.cpp \
../src/H263plusVideoRTPSink.cpp \
../src/H263plusVideoRTPSource.cpp \
../src/H264ParserSPS.cpp \
../src/H264VedioFileSink.cpp \
../src/H264VideoRTPSink.cpp \
../src/H264VideoRTPSource.cpp \
../src/H264VideoStreamDiscreteFramer.cpp \
../src/H264VideoStreamFramer.cpp \
../src/H264or5VedioFileSink.cpp \
../src/H264or5VideoRTPSink.cpp \
../src/H264or5VideoStreamDiscreteFramer.cpp \
../src/H264or5VideoStreamFramer.cpp \
../src/H265ParserSPS.cpp \
../src/H265VideoFileSink.cpp \
../src/H265VideoRTPSink.cpp \
../src/H265VideoRTPSource.cpp \
../src/H265VideoStreamDiscreteFramer.cpp \
../src/H265VideoStreamFramer.cpp \
../src/HandlerSet.cpp \
../src/HashTable.cpp \
../src/InputFile.cpp \
../src/JPEGVideoRTPSource.cpp \
../src/Locale.cpp \
../src/Logger.cpp \
../src/MEPG2TransportStreamFramer.cpp \
../src/MP3ADU.cpp \
../src/MP3ADURTPSink.cpp \
../src/MP3ADURTPSource.cpp \
../src/MP3ADUdescriptor.cpp \
../src/MP3ADUinterleaving.cpp \
../src/MP3InteralsHuffman.cpp \
../src/MP3Internals.cpp \
../src/MP3InternalsHuffmanTable.cpp \
../src/MPEG1or2AudioRTPSink.cpp \
../src/MPEG1or2AudioRTPSource.cpp \
../src/MPEG1or2Demux.cpp \
../src/MPEG1or2DemuxedElementaryStream.cpp \
../src/MPEG1or2VideoRTPSink.cpp \
../src/MPEG1or2VideoRTPSource.cpp \
../src/MPEG1or2VideoStreamDiscreteFramer.cpp \
../src/MPEG1or2VideoStreamFramer.cpp \
../src/MPEG2TransportStreamMultiplexor.cpp \
../src/MPEG4ESVideoRTPSink.cpp \
../src/MPEG4ESVideoRTPSource.cpp \
../src/MPEG4GenericRTPSink.cpp \
../src/MPEG4GenericRTPSource.cpp \
../src/MPEG4LATMAudioRTPSink.cpp \
../src/MPEG4LATMAudioRTPSource.cpp \
../src/MPEG4VideoStreamDiscreteFramer.cpp \
../src/MPEG4VideoStreamFramer.cpp \
../src/MPEGVideoStreamFramer.cpp \
../src/MPEGVideoStreamParser.cpp \
../src/Media.cpp \
../src/MediaSession.cpp \
../src/MediaSink.cpp \
../src/MediaSource.cpp \
../src/MultiFramedRTPSink.cpp \
../src/MultiFramedRTPSource.cpp \
../src/NetAddress.cpp \
../src/NetInterface.cpp \
../src/OggFileSink.cpp \
../src/OnDemandServerMediaSubsession.cpp \
../src/OutputFile.cpp \
../src/ProxyServerMediaSession.cpp \
../src/QCELPAudioRTPSource.cpp \
../src/QuickTimeFileSink.cpp \
../src/QuickTimeGenericRTPSource.cpp \
../src/RTCP.cpp \
../src/RTPInterface.cpp \
../src/RTPSink.cpp \
../src/RTPSource.cpp \
../src/RTSPClient.cpp \
../src/RTSPCommon.cpp \
../src/RTSPRegisterSender.cpp \
../src/RTSPServer.cpp \
../src/RTSPServerRegister.cpp \
../src/SIPClient.cpp \
../src/ServerMediaSession.cpp \
../src/SimpleRTPSink.cpp \
../src/SimpleRTPSource.cpp \
../src/StreamParser.cpp \
../src/T140TextRTPSink.cpp \
../src/TaskScheduler.cpp \
../src/TextRTPSink.cpp \
../src/TheoraVideoRTPSink.cpp \
../src/TheoraVideoRTPSource.cpp \
../src/UsageEnvironment.cpp \
../src/UsageEnvironment0.cpp \
../src/VP8VideoRTPSink.cpp \
../src/VP8VideoRTPSource.cpp \
../src/VP9VideoRTPSink.cpp \
../src/VP9VideoRTPSource.cpp \
../src/VideoRTPSink.cpp \
../src/VorbisAudioRTPSink.cpp \
../src/VorbisAudioRTPSource.cpp \
../src/main.cpp \
../src/openRTSP.cpp \
../src/ourMD5.cpp \
../src/playCommon.cpp \
../src/strDup.cpp \
../src/testRTSPClient.cpp 

C_SRCS += \
../src/inet.c \
../src/rtcp_from_spec.c 

OBJS += \
./src/AC3AudioRTPSink.o \
./src/AC3AudioRTPSource.o \
./src/AMRAudioFileSink.o \
./src/AMRAudioRTPSource.o \
./src/AMRAudioSource.o \
./src/AVIFileSink.o \
./src/AudioRTPSink.o \
./src/Base64.o \
./src/BasicHashTable.o \
./src/BasicTaskScheduler.o \
./src/BasicTaskScheduler0.o \
./src/BasicUDPSink.o \
./src/BasicUDPSource.o \
./src/BasicUsageEnvironment.o \
./src/BitVector.o \
./src/CommonPlay.o \
./src/CycleQueue.o \
./src/DP_RTSP_CLIENT_CycleQueue.o \
./src/DP_RTSP_CLIENT_DataQueue.o \
./src/DP_RTSP_CLIENT_Interface.o \
./src/DVVideoRTPSink.o \
./src/DVVideoRTPSource.o \
./src/DVVideoStreamFramer.o \
./src/DelayQueue.o \
./src/DigestAuthentication.o \
./src/FileSink.o \
./src/FramedFilter.o \
./src/FramedSource.o \
./src/GSMAudioRTPSink.o \
./src/GenericMediaServer.o \
./src/GetFrameData.o \
./src/GroupEId.o \
./src/Groupsock.o \
./src/GroupsockHelper.o \
./src/H261VideoRTPSource.o \
./src/H263plusVideoRTPSink.o \
./src/H263plusVideoRTPSource.o \
./src/H264ParserSPS.o \
./src/H264VedioFileSink.o \
./src/H264VideoRTPSink.o \
./src/H264VideoRTPSource.o \
./src/H264VideoStreamDiscreteFramer.o \
./src/H264VideoStreamFramer.o \
./src/H264or5VedioFileSink.o \
./src/H264or5VideoRTPSink.o \
./src/H264or5VideoStreamDiscreteFramer.o \
./src/H264or5VideoStreamFramer.o \
./src/H265ParserSPS.o \
./src/H265VideoFileSink.o \
./src/H265VideoRTPSink.o \
./src/H265VideoRTPSource.o \
./src/H265VideoStreamDiscreteFramer.o \
./src/H265VideoStreamFramer.o \
./src/HandlerSet.o \
./src/HashTable.o \
./src/InputFile.o \
./src/JPEGVideoRTPSource.o \
./src/Locale.o \
./src/Logger.o \
./src/MEPG2TransportStreamFramer.o \
./src/MP3ADU.o \
./src/MP3ADURTPSink.o \
./src/MP3ADURTPSource.o \
./src/MP3ADUdescriptor.o \
./src/MP3ADUinterleaving.o \
./src/MP3InteralsHuffman.o \
./src/MP3Internals.o \
./src/MP3InternalsHuffmanTable.o \
./src/MPEG1or2AudioRTPSink.o \
./src/MPEG1or2AudioRTPSource.o \
./src/MPEG1or2Demux.o \
./src/MPEG1or2DemuxedElementaryStream.o \
./src/MPEG1or2VideoRTPSink.o \
./src/MPEG1or2VideoRTPSource.o \
./src/MPEG1or2VideoStreamDiscreteFramer.o \
./src/MPEG1or2VideoStreamFramer.o \
./src/MPEG2TransportStreamMultiplexor.o \
./src/MPEG4ESVideoRTPSink.o \
./src/MPEG4ESVideoRTPSource.o \
./src/MPEG4GenericRTPSink.o \
./src/MPEG4GenericRTPSource.o \
./src/MPEG4LATMAudioRTPSink.o \
./src/MPEG4LATMAudioRTPSource.o \
./src/MPEG4VideoStreamDiscreteFramer.o \
./src/MPEG4VideoStreamFramer.o \
./src/MPEGVideoStreamFramer.o \
./src/MPEGVideoStreamParser.o \
./src/Media.o \
./src/MediaSession.o \
./src/MediaSink.o \
./src/MediaSource.o \
./src/MultiFramedRTPSink.o \
./src/MultiFramedRTPSource.o \
./src/NetAddress.o \
./src/NetInterface.o \
./src/OggFileSink.o \
./src/OnDemandServerMediaSubsession.o \
./src/OutputFile.o \
./src/ProxyServerMediaSession.o \
./src/QCELPAudioRTPSource.o \
./src/QuickTimeFileSink.o \
./src/QuickTimeGenericRTPSource.o \
./src/RTCP.o \
./src/RTPInterface.o \
./src/RTPSink.o \
./src/RTPSource.o \
./src/RTSPClient.o \
./src/RTSPCommon.o \
./src/RTSPRegisterSender.o \
./src/RTSPServer.o \
./src/RTSPServerRegister.o \
./src/SIPClient.o \
./src/ServerMediaSession.o \
./src/SimpleRTPSink.o \
./src/SimpleRTPSource.o \
./src/StreamParser.o \
./src/T140TextRTPSink.o \
./src/TaskScheduler.o \
./src/TextRTPSink.o \
./src/TheoraVideoRTPSink.o \
./src/TheoraVideoRTPSource.o \
./src/UsageEnvironment.o \
./src/UsageEnvironment0.o \
./src/VP8VideoRTPSink.o \
./src/VP8VideoRTPSource.o \
./src/VP9VideoRTPSink.o \
./src/VP9VideoRTPSource.o \
./src/VideoRTPSink.o \
./src/VorbisAudioRTPSink.o \
./src/VorbisAudioRTPSource.o \
./src/inet.o \
./src/main.o \
./src/openRTSP.o \
./src/ourMD5.o \
./src/playCommon.o \
./src/rtcp_from_spec.o \
./src/strDup.o \
./src/testRTSPClient.o 

CPP_DEPS += \
./src/AC3AudioRTPSink.d \
./src/AC3AudioRTPSource.d \
./src/AMRAudioFileSink.d \
./src/AMRAudioRTPSource.d \
./src/AMRAudioSource.d \
./src/AVIFileSink.d \
./src/AudioRTPSink.d \
./src/Base64.d \
./src/BasicHashTable.d \
./src/BasicTaskScheduler.d \
./src/BasicTaskScheduler0.d \
./src/BasicUDPSink.d \
./src/BasicUDPSource.d \
./src/BasicUsageEnvironment.d \
./src/BitVector.d \
./src/CommonPlay.d \
./src/CycleQueue.d \
./src/DP_RTSP_CLIENT_CycleQueue.d \
./src/DP_RTSP_CLIENT_DataQueue.d \
./src/DP_RTSP_CLIENT_Interface.d \
./src/DVVideoRTPSink.d \
./src/DVVideoRTPSource.d \
./src/DVVideoStreamFramer.d \
./src/DelayQueue.d \
./src/DigestAuthentication.d \
./src/FileSink.d \
./src/FramedFilter.d \
./src/FramedSource.d \
./src/GSMAudioRTPSink.d \
./src/GenericMediaServer.d \
./src/GetFrameData.d \
./src/GroupEId.d \
./src/Groupsock.d \
./src/GroupsockHelper.d \
./src/H261VideoRTPSource.d \
./src/H263plusVideoRTPSink.d \
./src/H263plusVideoRTPSource.d \
./src/H264ParserSPS.d \
./src/H264VedioFileSink.d \
./src/H264VideoRTPSink.d \
./src/H264VideoRTPSource.d \
./src/H264VideoStreamDiscreteFramer.d \
./src/H264VideoStreamFramer.d \
./src/H264or5VedioFileSink.d \
./src/H264or5VideoRTPSink.d \
./src/H264or5VideoStreamDiscreteFramer.d \
./src/H264or5VideoStreamFramer.d \
./src/H265ParserSPS.d \
./src/H265VideoFileSink.d \
./src/H265VideoRTPSink.d \
./src/H265VideoRTPSource.d \
./src/H265VideoStreamDiscreteFramer.d \
./src/H265VideoStreamFramer.d \
./src/HandlerSet.d \
./src/HashTable.d \
./src/InputFile.d \
./src/JPEGVideoRTPSource.d \
./src/Locale.d \
./src/Logger.d \
./src/MEPG2TransportStreamFramer.d \
./src/MP3ADU.d \
./src/MP3ADURTPSink.d \
./src/MP3ADURTPSource.d \
./src/MP3ADUdescriptor.d \
./src/MP3ADUinterleaving.d \
./src/MP3InteralsHuffman.d \
./src/MP3Internals.d \
./src/MP3InternalsHuffmanTable.d \
./src/MPEG1or2AudioRTPSink.d \
./src/MPEG1or2AudioRTPSource.d \
./src/MPEG1or2Demux.d \
./src/MPEG1or2DemuxedElementaryStream.d \
./src/MPEG1or2VideoRTPSink.d \
./src/MPEG1or2VideoRTPSource.d \
./src/MPEG1or2VideoStreamDiscreteFramer.d \
./src/MPEG1or2VideoStreamFramer.d \
./src/MPEG2TransportStreamMultiplexor.d \
./src/MPEG4ESVideoRTPSink.d \
./src/MPEG4ESVideoRTPSource.d \
./src/MPEG4GenericRTPSink.d \
./src/MPEG4GenericRTPSource.d \
./src/MPEG4LATMAudioRTPSink.d \
./src/MPEG4LATMAudioRTPSource.d \
./src/MPEG4VideoStreamDiscreteFramer.d \
./src/MPEG4VideoStreamFramer.d \
./src/MPEGVideoStreamFramer.d \
./src/MPEGVideoStreamParser.d \
./src/Media.d \
./src/MediaSession.d \
./src/MediaSink.d \
./src/MediaSource.d \
./src/MultiFramedRTPSink.d \
./src/MultiFramedRTPSource.d \
./src/NetAddress.d \
./src/NetInterface.d \
./src/OggFileSink.d \
./src/OnDemandServerMediaSubsession.d \
./src/OutputFile.d \
./src/ProxyServerMediaSession.d \
./src/QCELPAudioRTPSource.d \
./src/QuickTimeFileSink.d \
./src/QuickTimeGenericRTPSource.d \
./src/RTCP.d \
./src/RTPInterface.d \
./src/RTPSink.d \
./src/RTPSource.d \
./src/RTSPClient.d \
./src/RTSPCommon.d \
./src/RTSPRegisterSender.d \
./src/RTSPServer.d \
./src/RTSPServerRegister.d \
./src/SIPClient.d \
./src/ServerMediaSession.d \
./src/SimpleRTPSink.d \
./src/SimpleRTPSource.d \
./src/StreamParser.d \
./src/T140TextRTPSink.d \
./src/TaskScheduler.d \
./src/TextRTPSink.d \
./src/TheoraVideoRTPSink.d \
./src/TheoraVideoRTPSource.d \
./src/UsageEnvironment.d \
./src/UsageEnvironment0.d \
./src/VP8VideoRTPSink.d \
./src/VP8VideoRTPSource.d \
./src/VP9VideoRTPSink.d \
./src/VP9VideoRTPSource.d \
./src/VideoRTPSink.d \
./src/VorbisAudioRTPSink.d \
./src/VorbisAudioRTPSource.d \
./src/main.d \
./src/openRTSP.d \
./src/ourMD5.d \
./src/playCommon.d \
./src/strDup.d \
./src/testRTSPClient.d 

C_DEPS += \
./src/inet.d \
./src/rtcp_from_spec.d 


# Each subdirectory must supply rules for building sources it contributes
src/%.o: ../src/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/include -I/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include -include/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include/Rtsp_server.h -include/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include/Rtsp_sys.h -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<" -Wno-unused
	@echo 'Finished building: $<'
	@echo ' '

src/%.o: ../src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I"/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/include" -I"/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include" -include/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include/Rtsp_server.h -include"/home/jhb/nfs/TerminalC++Workspace/RTSP_Client/X86/include/Rtsp_sys.h" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


